AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Type: String
    Default: 'transcodekit'


Resources:
  TranscodekitUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: transcodekit
      Groups:
        - !Ref TranscodekitAdmins

  TranscodekitAdmins:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: TranscodekitAdmins
      ManagedPolicyArns:
        - !Ref TranscodekitS3Admin

  TranscodekitAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref TranscodekitUser

  TranscodekitS3Admin:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Join
        - '-'
        - - !Ref 'AWS::Region'
          - TranscodekitS3Admin
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName


Outputs:
  AccessKey:
    Value: !Ref TranscodekitAccessKey
  SecretAccessKey:
    Value: !GetAtt TranscodekitAccessKey.SecretAccessKey
